dataset_name: BramVanroy/xlwic_wn
dataset_config: nl
labels2idx:
  anders: 0
  hetzelfde: 1
prompt: |-
  Is de betekenis van '{target_word}' in de twee volgende Nederlandstalige zinnen hetzelfde of anders?

  Zin 1: {example_1}
  Zin 2: {example_2}

  Antwoord met 'anders' of 'hetzelfde'.
output_dir: results/benchmarks/xlwic_wn-nl/boreas-7b
model_name: yhavinga/Boreas-7B
dataset_split: test
label_column: label
f1_average: macro
use_chat_template: false
bnb_config:
model_kwargs:
  torch_dtype: auto
device: auto
batch_size: 2
num_workers: 36
