dataset_name: BramVanroy/xlwic_wn
dataset_config: nl
labels2idx:
  verschillend: 0
  identiek: 1
prompt: |-
  Is de betekenis van '{target_word}' in de volgende zinnen identiek of verschillend?

  Zin 1: {example_1}
  Zin 2: {example_2}

  Antwoord met 'identiek' of 'verschillend'.
output_dir: results/benchmarks/xlwic_wn-nl/geitje-7b-ultra
model_name: BramVanroy/GEITje-7B-ultra
dataset_split: test
label_column: label
f1_average: macro
system_message: ''
use_chat_template: true
bnb_config:
model_kwargs:
  torch_dtype: auto
device: auto
batch_size: 2
num_workers: 36
num_runs: 5
