dataset_name: BramVanroy/xlwic_wn
dataset_config: nl
labels2idx:
  anders: 0
  hetzelfde: 1
prompt: "Is de betekenis van '{target_word}' in de twee volgende Nederlandstalige zinnen hetzelfde of anders?\n\nZin 1: {example_1}\nZin 2: {example_2}"
output_dir: results/xlwic_wn-nl/qwen2-0-5b
model_name: Qwen/Qwen2-0.5B
dataset_split: test
label_column: label
f1_average: macro
use_chat_template: false
bnb_config: null
model_kwargs:
  torch_dtype: auto
device: auto
batch_size: 1
