dataset_name: dbrd
labels2idx:
  negatief: 0
  positief: 1
prompt: "Is het sentiment in de volgende Nederlandstalige boekrecensie positief of negatief?\n\n{text}"
output_dir: results/dbrd/kwinten-0-5b
model_name: BramVanroy/kwinten-0.5b
dataset_config: null
dataset_split: test
label_column: label
f1_average: macro
use_chat_template: false
bnb_config: null
model_kwargs:
  torch_dtype: auto
device: auto
batch_size: 1
