dataset_name: dbrd
labels2idx:
  negatief: 0
  positief: 1
prompt: |-
  Is het sentiment in de volgende Nederlandstalige boekrecensie positief of negatief?

  Boekrecensie: {text}

  Antwoord met 'positief' of 'negatief'.
output_dir: results/benchmarks/dbrd/mistral-7b-instruct-v01
model_name: mistralai/Mistral-7B-Instruct-v0.1
dataset_config:
dataset_split: test
label_column: label
f1_average: macro
system_message: ''
use_chat_template: true
bnb_config:
model_kwargs:
  torch_dtype: auto
device: auto
batch_size: 2
num_workers: 36
