dataset_name: dbrd
labels2idx:
  negatief: 0
  positief: 1
prompt: "Is het sentiment in de volgende Nederlandstalige boekrecensie positief of negatief?\n\n{text}"
output_dir: results/dbrd/qwen1.5-7b-dutch-chat
model_name: robinsmits/Qwen1.5-7B-Dutch-Chat
dataset_config: null
dataset_split: test
label_column: label
f1_average: macro
system_message: ""
use_chat_template: true
bnb_config: null
model_kwargs:
  torch_dtype: auto
device: auto
batch_size: 2
