batch_size: 4
bnb_config: null
convert_labels_to_int: true
dataset_config: nl
dataset_name: alexandrainst/scala
dataset_split: test
device: auto
f1_average: macro
label_column: label
labels2idx:
  correct: 1
  incorrect: 0
model_kwargs:
  torch_dtype: auto
model_name: BramVanroy/GEITje-7B-ultra
output_dir: results/benchmarks/scala/geitje-7b-ultra
prompt: 'Is de volgende tekst grammaticaal correct of incorrect?


  Tekst: {text}


  Antwoord met ''correct'' of ''incorrect''.'
system_message: ''
use_chat_template: true
