dataset_name: GroNLP/dutch-cola
labels2idx:
  ongrammaticaal: 0
  grammaticaal: 1
prompt: |-
  Is de volgende tekst grammaticaal (correct Nederlands) of ongrammaticaal (onjuist Nederlands)?

  Tekst: {Sentence}

  Antwoord met 'grammaticaal' of 'ongrammaticaal'. De tekst is 
output_dir: results/benchmarks/dutch-cola/boreas-7b
model_name: yhavinga/Boreas-7B
dataset_config:
dataset_split: test
label_column: Acceptability
f1_average: macro
use_chat_template: false
bnb_config:
model_kwargs:
  torch_dtype: auto
device: auto
batch_size: 2
num_workers: 36
num_runs: 5
