dataset_name: GroNLP/dutch-cola
labels2idx:
  incorrect: 0
  correct: 1
prompt: "Is de volgende Nederlandstalige zin grammaticaal correct of incorrect?\n\n{Sentence}"
output_dir: results/dutch-cola/fietje-2b-instruct
model_name: BramVanroy/fietje-2b-instruct
dataset_config: null
dataset_split: test
label_column: Acceptability
f1_average: macro
system_message: ""
use_chat_template: true
bnb_config: null
model_kwargs:
  torch_dtype: auto
device: auto
batch_size: 2
