dataset_name: GroNLP/dutch-cola
labels2idx:
  incorrect: 0
  correct: 1
prompt: "Is de volgende Nederlandstalige zin grammaticaal correct of incorrect?\n\n{Sentence}"
output_dir: results/dutch-cola/phi-2
model_name: microsoft/phi-2
dataset_config: null
dataset_split: test
label_column: Acceptability
f1_average: macro
use_chat_template: false
bnb_config: null
model_kwargs:
  torch_dtype: auto
device: auto
batch_size: 2
